#encoding: utf-8
namespace :chile_data do
  desc "fills table regions and communes"
  task :load => :environment do
  	Region.delete_all
  	Region.create(:name => 'Región de Tarapacá')
  	Region.create(:name => 'Región de Antofagasta')
  	Region.create(:name => 'Región de Atacama')
  	Region.create(:name => 'Región de Coquimbo')
  	Region.create(:name => 'Región de Valparaiso')
  	Region.create(:name => 'Región del Libertador General Bernardo O Higgins')
  	Region.create(:name => 'Región del Maule')
  	Region.create(:name => 'Región del Bío-Bío')
  	Region.create(:name => 'Región de la Araucanía')
  	Region.create(:name => 'Región de Los Lagos')
  	Region.create(:name => 'Región de Aysén del General Carlos Ibáñez del Campo')
  	Region.create(:name => 'Región de Magallanes y la Antártica Chilena')
  	Region.create(:name => 'Región de Metropolitana')
  	Region.create(:name => 'Región de Los Ríos')
  	Region.create(:name => 'Región de Arica y Parinacota')

  	Commune.delete_all
  	Commune.create(:name => 'ALTO HOSPICIO', :region_id => 1)
	Commune.create(:name => 'CAMINA', :region_id => 1)
	Commune.create(:name => 'COLCHANE', :region_id => 1)
	Commune.create(:name => 'HUARA', :region_id => 1)
	Commune.create(:name => 'IQUIQUE', :region_id => 1)
	Commune.create(:name => 'PICA', :region_id => 1)
	Commune.create(:name => 'POZO ALMONTE', :region_id => 1)
	Commune.create(:name => 'ANTOFAGASTA', :region_id => 2)
	Commune.create(:name => 'CALAMA', :region_id => 2)
	Commune.create(:name => 'MARIA ELENA', :region_id => 2)
	Commune.create(:name => 'MEJILLONES', :region_id => 2)
	Commune.create(:name => 'OLLAGÜE', :region_id => 2)
	Commune.create(:name => 'SAN PEDRO DE ATACAMA', :region_id => 2)
	Commune.create(:name => 'SIERRA GORDA', :region_id => 2)
	Commune.create(:name => 'TALTAL', :region_id => 2)
	Commune.create(:name => 'TOCOPILLA', :region_id => 2)
	Commune.create(:name => 'ALTO DEL CARMEN', :region_id => 3)
	Commune.create(:name => 'CALDERA', :region_id => 3)
	Commune.create(:name => 'CHAÑARAL', :region_id => 3)
	Commune.create(:name => 'COPIAPO', :region_id => 3)
	Commune.create(:name => 'DIEGO DE ALMAGRO', :region_id => 3)
	Commune.create(:name => 'FREIRINA', :region_id => 3)
	Commune.create(:name => 'HUASCO', :region_id => 3)
	Commune.create(:name => 'TIERRA AMARILLA', :region_id => 3)
	Commune.create(:name => 'VALLENAR', :region_id => 3)
	Commune.create(:name => 'ANDACOLLO', :region_id => 4)
	Commune.create(:name => 'CANELA', :region_id => 4)
	Commune.create(:name => 'COMBARBALA', :region_id => 4)
	Commune.create(:name => 'COQUIMBO', :region_id => 4)
	Commune.create(:name => 'ILLAPEL', :region_id => 4)
	Commune.create(:name => 'LA HIGUERA', :region_id => 4)
	Commune.create(:name => 'LA SERENA', :region_id => 4)
	Commune.create(:name => 'LOS VILOS', :region_id => 4)
	Commune.create(:name => 'MONTE PATRIA', :region_id => 4)
	Commune.create(:name => 'OVALLE', :region_id => 4)
	Commune.create(:name => 'PAIHUANO', :region_id => 4)
	Commune.create(:name => 'PUNITAQUI', :region_id => 4)
	Commune.create(:name => 'RIO HURTADO', :region_id => 4)
	Commune.create(:name => 'SALAMANCA', :region_id => 4)
	Commune.create(:name => 'VICUÑA', :region_id => 4)
	Commune.create(:name => 'ALGARROBO', :region_id => 5)
	Commune.create(:name => 'CABILDO', :region_id => 5)
	Commune.create(:name => 'CALLE LARGA', :region_id => 5)
	Commune.create(:name => 'CARTAGENA', :region_id => 5)
	Commune.create(:name => 'CASABLANCA', :region_id => 5)
	Commune.create(:name => 'CATEMU', :region_id => 5)
	Commune.create(:name => 'CONCON', :region_id => 5)
	Commune.create(:name => 'EL QUISCO', :region_id => 5)
	Commune.create(:name => 'EL TABO', :region_id => 5)
	Commune.create(:name => 'HIJUELAS', :region_id => 5)
	Commune.create(:name => 'ISLA DE PASCUA', :region_id => 5)
	Commune.create(:name => 'JUAN FERNANDEZ', :region_id => 5)
	Commune.create(:name => 'LA CALERA', :region_id => 5)
	Commune.create(:name => 'LA CRUZ', :region_id => 5)
	Commune.create(:name => 'LA LIGUA', :region_id => 5)
	Commune.create(:name => 'LIMACHE', :region_id => 5)
	Commune.create(:name => 'LLAY LLAY', :region_id => 5)
	Commune.create(:name => 'LOS ANDES', :region_id => 5)
	Commune.create(:name => 'NOGALES', :region_id => 5)
	Commune.create(:name => 'OLMUE', :region_id => 5)
	Commune.create(:name => 'PANQUEHUE', :region_id => 5)
	Commune.create(:name => 'PAPUDO', :region_id => 5)
	Commune.create(:name => 'PETORCA', :region_id => 5)
	Commune.create(:name => 'PUCHUNCAVI', :region_id => 5)
	Commune.create(:name => 'PUTAENDO', :region_id => 5)
	Commune.create(:name => 'QUILLOTA', :region_id => 5)
	Commune.create(:name => 'QUILPUE', :region_id => 5)
	Commune.create(:name => 'QUINTERO', :region_id => 5)
	Commune.create(:name => 'RINCONADA', :region_id => 5)
	Commune.create(:name => 'SAN ANTONIO', :region_id => 5)
	Commune.create(:name => 'SAN ESTEBAN', :region_id => 5)
	Commune.create(:name => 'SAN FELIPE', :region_id => 5)
	Commune.create(:name => 'SANTA MARIA', :region_id => 5)
	Commune.create(:name => 'SANTO DOMINGO', :region_id => 5)
	Commune.create(:name => 'VALPARAISO', :region_id => 5)
	Commune.create(:name => 'VILLA ALEMANA', :region_id => 5)
	Commune.create(:name => 'VIÑA DEL MAR', :region_id => 5)
	Commune.create(:name => 'ZAPALLAR', :region_id => 5)
	Commune.create(:name => 'CHEPICA', :region_id => 6)
	Commune.create(:name => 'CHIMBARONGO', :region_id => 6)
	Commune.create(:name => 'CODEGUA', :region_id => 6)
	Commune.create(:name => 'COINCO', :region_id => 6)
	Commune.create(:name => 'COLTAUCO', :region_id => 6)
	Commune.create(:name => 'DOÑIHUE', :region_id => 6)
	Commune.create(:name => 'GRANEROS', :region_id => 6)
	Commune.create(:name => 'LA ESTRELLA', :region_id => 6)
	Commune.create(:name => 'LAS CABRAS', :region_id => 6)
	Commune.create(:name => 'LITUECHE', :region_id => 6)
	Commune.create(:name => 'LOLOL', :region_id => 6)
	Commune.create(:name => 'MACHALI', :region_id => 6)
	Commune.create(:name => 'MALLOA', :region_id => 6)
	Commune.create(:name => 'MARCHIGUE', :region_id => 6)
	Commune.create(:name => 'NANCAGUA', :region_id => 6)
	Commune.create(:name => 'NAVIDAD', :region_id => 6)
	Commune.create(:name => 'OLIVAR', :region_id => 6)
	Commune.create(:name => 'PALMILLA', :region_id => 6)
	Commune.create(:name => 'PAREDONES', :region_id => 6)
	Commune.create(:name => 'PERALILLO', :region_id => 6)
	Commune.create(:name => 'PEUMO', :region_id => 6)
	Commune.create(:name => 'PICHIDEGUA', :region_id => 6)
	Commune.create(:name => 'PICHILEMU', :region_id => 6)
	Commune.create(:name => 'PLACILLA', :region_id => 6)
	Commune.create(:name => 'PUMANQUE', :region_id => 6)
	Commune.create(:name => 'QUINTA DE TILCOCO', :region_id => 6)
	Commune.create(:name => 'RANCAGUA', :region_id => 6)
	Commune.create(:name => 'RENGO', :region_id => 6)
	Commune.create(:name => 'REQUINOA', :region_id => 6)
	Commune.create(:name => 'SAN FERNANDO', :region_id => 6)
	Commune.create(:name => 'SAN FRANCISCO DE MOSTAZAL', :region_id => 6)
	Commune.create(:name => 'SAN VICENTE', :region_id => 6)
	Commune.create(:name => 'SANTA CRUZ', :region_id => 6)
	Commune.create(:name => 'CAUQUENES', :region_id => 7)
	Commune.create(:name => 'CHANCO', :region_id => 7)
	Commune.create(:name => 'COLBUN', :region_id => 7)
	Commune.create(:name => 'CONSTITUCION', :region_id => 7)
	Commune.create(:name => 'CUREPTO', :region_id => 7)
	Commune.create(:name => 'CURICO', :region_id => 7)
	Commune.create(:name => 'EMPEDRADO', :region_id => 7)
	Commune.create(:name => 'HUALAÑE', :region_id => 7)
	Commune.create(:name => 'LICANTEN', :region_id => 7)
	Commune.create(:name => 'LINARES', :region_id => 7)
	Commune.create(:name => 'LONGAVI', :region_id => 7)
	Commune.create(:name => 'MAULE', :region_id => 7)
	Commune.create(:name => 'MOLINA', :region_id => 7)
	Commune.create(:name => 'PARRAL', :region_id => 7)
	Commune.create(:name => 'PELARCO', :region_id => 7)
	Commune.create(:name => 'PELLUHUE', :region_id => 7)
	Commune.create(:name => 'PENCAHUE', :region_id => 7)
	Commune.create(:name => 'RAUCO', :region_id => 7)
	Commune.create(:name => 'RETIRO', :region_id => 7)
	Commune.create(:name => 'RIO CLARO', :region_id => 7)
	Commune.create(:name => 'ROMERAL', :region_id => 7)
	Commune.create(:name => 'SAGRADA FAMILIA', :region_id => 7)
	Commune.create(:name => 'SAN CLEMENTE', :region_id => 7)
	Commune.create(:name => 'SAN JAVIER', :region_id => 7)
	Commune.create(:name => 'SAN RAFAEL', :region_id => 7)
	Commune.create(:name => 'TALCA', :region_id => 7)
	Commune.create(:name => 'TENO', :region_id => 7)
	Commune.create(:name => 'VICHUQUEN', :region_id => 7)
	Commune.create(:name => 'VILLA ALEGRE', :region_id => 7)
	Commune.create(:name => 'YERBAS BUENAS', :region_id => 7)
	Commune.create(:name => 'ANTUCO', :region_id => 8)
	Commune.create(:name => 'ARAUCO', :region_id => 8)
	Commune.create(:name => 'BULNES', :region_id => 8)
	Commune.create(:name => 'CABRERO', :region_id => 8)
	Commune.create(:name => 'CAÑETE', :region_id => 8)
	Commune.create(:name => 'CHIGUAYANTE', :region_id => 8)
	Commune.create(:name => 'CHILLAN', :region_id => 8)
	Commune.create(:name => 'CHILLAN VIEJO', :region_id => 8)
	Commune.create(:name => 'COBQUECURA', :region_id => 8)
	Commune.create(:name => 'COELEMU', :region_id => 8)
	Commune.create(:name => 'COIHUECO', :region_id => 8)
	Commune.create(:name => 'CONCEPCION', :region_id => 8)
	Commune.create(:name => 'CONTULMO', :region_id => 8)
	Commune.create(:name => 'CORONEL', :region_id => 8)
	Commune.create(:name => 'CURANILAHUE', :region_id => 8)
	Commune.create(:name => 'EL CARMEN', :region_id => 8)
	Commune.create(:name => 'FLORIDA', :region_id => 8)
	Commune.create(:name => 'HUALQUI', :region_id => 8)
	Commune.create(:name => 'LAJA', :region_id => 8)
	Commune.create(:name => 'LEBU', :region_id => 8)
	Commune.create(:name => 'LOS ALAMOS', :region_id => 8)
	Commune.create(:name => 'LOS ANGELES', :region_id => 8)
	Commune.create(:name => 'LOTA', :region_id => 8)
	Commune.create(:name => 'MULCHEN', :region_id => 8)
	Commune.create(:name => 'NACIMIENTO', :region_id => 8)
	Commune.create(:name => 'NEGRETE', :region_id => 8)
	Commune.create(:name => 'NINHUE', :region_id => 8)
	Commune.create(:name => 'PEMUCO', :region_id => 8)
	Commune.create(:name => 'PENCO', :region_id => 8)
	Commune.create(:name => 'PINTO', :region_id => 8)
	Commune.create(:name => 'PORTEZUELO', :region_id => 8)
	Commune.create(:name => 'QUILACO', :region_id => 8)
	Commune.create(:name => 'QUILLECO', :region_id => 8)
	Commune.create(:name => 'QUILLON', :region_id => 8)
	Commune.create(:name => 'QUIRIHUE', :region_id => 8)
	Commune.create(:name => 'RANQUIL', :region_id => 8)
	Commune.create(:name => 'SAN CARLOS', :region_id => 8)
	Commune.create(:name => 'SAN FABIAN', :region_id => 8)
	Commune.create(:name => 'SAN GREGORIO DE ÑIQUEN', :region_id => 8)
	Commune.create(:name => 'SAN IGNACIO', :region_id => 8)
	Commune.create(:name => 'SAN NICOLAS', :region_id => 8)
	Commune.create(:name => 'SAN PEDRO DE LA PAZ', :region_id => 8)
	Commune.create(:name => 'SAN ROSENDO', :region_id => 8)
	Commune.create(:name => 'SANTA BARBARA', :region_id => 8)
	Commune.create(:name => 'SANTA JUANA', :region_id => 8)
	Commune.create(:name => 'TALCAHUANO', :region_id => 8)
	Commune.create(:name => 'TIRUA', :region_id => 8)
	Commune.create(:name => 'TOME', :region_id => 8)
	Commune.create(:name => 'TREHUACO', :region_id => 8)
	Commune.create(:name => 'TUCAPEL', :region_id => 8)
	Commune.create(:name => 'YUMBEL', :region_id => 8)
	Commune.create(:name => 'YUNGAY', :region_id => 8)
	Commune.create(:name => 'ANGOL', :region_id => 9)
	Commune.create(:name => 'CARAHUE', :region_id => 9)
	Commune.create(:name => 'COLLIPULLI', :region_id => 9)
	Commune.create(:name => 'CUNCO', :region_id => 9)
	Commune.create(:name => 'CURACAUTIN', :region_id => 9)
	Commune.create(:name => 'CURARREHUE', :region_id => 9)
	Commune.create(:name => 'ERCILLA', :region_id => 9)
	Commune.create(:name => 'FREIRE', :region_id => 9)
	Commune.create(:name => 'GALVARINO', :region_id => 9)
	Commune.create(:name => 'GORBEA', :region_id => 9)
	Commune.create(:name => 'LAUTARO', :region_id => 9)
	Commune.create(:name => 'LONCOCHE', :region_id => 9)
	Commune.create(:name => 'LONQUIMAY', :region_id => 9)
	Commune.create(:name => 'LOS SAUCES', :region_id => 9)
	Commune.create(:name => 'LUMACO', :region_id => 9)
	Commune.create(:name => 'MELIPEUCO', :region_id => 9)
	Commune.create(:name => 'NUEVA IMPERIAL', :region_id => 9)
	Commune.create(:name => 'PADRE LAS CASAS', :region_id => 9)
	Commune.create(:name => 'PERQUENCO', :region_id => 9)
	Commune.create(:name => 'PITRUFQUEN', :region_id => 9)
	Commune.create(:name => 'PUCON', :region_id => 9)
	Commune.create(:name => 'PUERTO SAAVEDRA', :region_id => 9)
	Commune.create(:name => 'PUREN', :region_id => 9)
	Commune.create(:name => 'RENAICO', :region_id => 9)
	Commune.create(:name => 'TEMUCO', :region_id => 9)
	Commune.create(:name => 'TEODORO SCHMIDT', :region_id => 9)
	Commune.create(:name => 'TOLTEN', :region_id => 9)
	Commune.create(:name => 'TRAIGUEN', :region_id => 9)
	Commune.create(:name => 'VICTORIA', :region_id => 9)
	Commune.create(:name => 'VILCUN', :region_id => 9)
	Commune.create(:name => 'VILLARRICA', :region_id => 9)
	Commune.create(:name => 'ANCUD', :region_id => 10)
	Commune.create(:name => 'CALBUCO', :region_id => 10)
	Commune.create(:name => 'CASTRO', :region_id => 10)
	Commune.create(:name => 'CHAITEN', :region_id => 10)
	Commune.create(:name => 'CHONCHI', :region_id => 10)
	Commune.create(:name => 'COCHAMO', :region_id => 10)
	Commune.create(:name => 'CURACO DE VELEZ', :region_id => 10)
	Commune.create(:name => 'DALCAHUE', :region_id => 10)
	Commune.create(:name => 'FRESIA', :region_id => 10)
	Commune.create(:name => 'FRUTILLAR', :region_id => 10)
	Commune.create(:name => 'FUTALEUFU', :region_id => 10)
	Commune.create(:name => 'HUALAIHUE', :region_id => 10)
	Commune.create(:name => 'LLANQUIHUE', :region_id => 10)
	Commune.create(:name => 'LOS MUERMOS', :region_id => 10)
	Commune.create(:name => 'MAULLIN', :region_id => 10)
	Commune.create(:name => 'OSORNO', :region_id => 10)
	Commune.create(:name => 'PALENA', :region_id => 10)
	Commune.create(:name => 'PUERTO MONTT', :region_id => 10)
	Commune.create(:name => 'PUERTO OCTAY', :region_id => 10)
	Commune.create(:name => 'PUERTO VARAS', :region_id => 10)
	Commune.create(:name => 'PUQUELDON', :region_id => 10)
	Commune.create(:name => 'PURRANQUE', :region_id => 10)
	Commune.create(:name => 'PUYEHUE', :region_id => 10)
	Commune.create(:name => 'QUEILEN', :region_id => 10)
	Commune.create(:name => 'QUELLON', :region_id => 10)
	Commune.create(:name => 'QUEMCHI', :region_id => 10)
	Commune.create(:name => 'QUINCHAO', :region_id => 10)
	Commune.create(:name => 'RIO NEGRO', :region_id => 10)
	Commune.create(:name => 'SAN JUAN DE LA COSTA', :region_id => 10)
	Commune.create(:name => 'SAN PABLO', :region_id => 10)
	Commune.create(:name => 'AYSEN', :region_id => 11)
	Commune.create(:name => 'CHILE CHICO', :region_id => 11)
	Commune.create(:name => 'CISNES', :region_id => 11)
	Commune.create(:name => 'COCHRANE', :region_id => 11)
	Commune.create(:name => 'COYHAIQUE', :region_id => 11)
	Commune.create(:name => 'GUAITECAS', :region_id => 11)
	Commune.create(:name => 'LAGO VERDE', :region_id => 11)
	Commune.create(:name => 'O´HIGGINS', :region_id => 11)
	Commune.create(:name => 'RIO IBAÑEZ', :region_id => 11)
	Commune.create(:name => 'TORTEL', :region_id => 11)
	Commune.create(:name => 'LAGUNA BLANCA', :region_id => 12)
	Commune.create(:name => 'NAVARINO', :region_id => 12)
	Commune.create(:name => 'PORVENIR', :region_id => 12)
	Commune.create(:name => 'PRIMAVERA', :region_id => 12)
	Commune.create(:name => 'PUERTO NATALES', :region_id => 12)
	Commune.create(:name => 'PUNTA ARENAS', :region_id => 12)
	Commune.create(:name => 'RIO VERDE', :region_id => 12)
	Commune.create(:name => 'SAN GREGORIO', :region_id => 12)
	Commune.create(:name => 'TIMAUKEL', :region_id => 12)
	Commune.create(:name => 'TORRES DEL PAINE', :region_id => 12)
	Commune.create(:name => 'ALHUE', :region_id => 13)
	Commune.create(:name => 'BUIN', :region_id => 13)
	Commune.create(:name => 'CALERA DE TANGO', :region_id => 13)
	Commune.create(:name => 'CERRILLOS', :region_id => 13)
	Commune.create(:name => 'CERRO NAVIA', :region_id => 13)
	Commune.create(:name => 'COLINA', :region_id => 13)
	Commune.create(:name => 'CONCHALI', :region_id => 13)
	Commune.create(:name => 'CURACAVI', :region_id => 13)
	Commune.create(:name => 'EL BOSQUE', :region_id => 13)
	Commune.create(:name => 'EL MONTE', :region_id => 13)
	Commune.create(:name => 'ESTACION CENTRAL', :region_id => 13)
	Commune.create(:name => 'HUECHURABA', :region_id => 13)
	Commune.create(:name => 'INDEPENDENCIA', :region_id => 13)
	Commune.create(:name => 'ISLA DE MAIPO', :region_id => 13)
	Commune.create(:name => 'LA CISTERNA', :region_id => 13)
	Commune.create(:name => 'LA FLORIDA', :region_id => 13)
	Commune.create(:name => 'LA GRANJA', :region_id => 13)
	Commune.create(:name => 'LA PINTANA', :region_id => 13)
	Commune.create(:name => 'LA REINA', :region_id => 13)
	Commune.create(:name => 'LAMPA', :region_id => 13)
	Commune.create(:name => 'LAS CONDES', :region_id => 13)
	Commune.create(:name => 'LO BARNECHEA', :region_id => 13)
	Commune.create(:name => 'LO ESPEJO', :region_id => 13)
	Commune.create(:name => 'LO PRADO', :region_id => 13)
	Commune.create(:name => 'MACUL', :region_id => 13)
	Commune.create(:name => 'MAIPU', :region_id => 13)
	Commune.create(:name => 'MARIA PINTO', :region_id => 13)
	Commune.create(:name => 'MELIPILLA', :region_id => 13)
	Commune.create(:name => 'ÑUÑOA', :region_id => 13)
	Commune.create(:name => 'PADRE HURTADO', :region_id => 13)
	Commune.create(:name => 'PAINE', :region_id => 13)
	Commune.create(:name => 'PEDRO AGUIRRE CERDA', :region_id => 13)
	Commune.create(:name => 'PEÑAFLOR', :region_id => 13)
	Commune.create(:name => 'PEÑALOLEN', :region_id => 13)
	Commune.create(:name => 'PIRQUE', :region_id => 13)
	Commune.create(:name => 'PROVIDENCIA', :region_id => 13)
	Commune.create(:name => 'PUDAHUEL', :region_id => 13)
	Commune.create(:name => 'PUENTE ALTO', :region_id => 13)
	Commune.create(:name => 'QUILICURA', :region_id => 13)
	Commune.create(:name => 'QUINTA NORMAL', :region_id => 13)
	Commune.create(:name => 'RECOLETA', :region_id => 13)
	Commune.create(:name => 'RENCA', :region_id => 13)
	Commune.create(:name => 'SAN BERNARDO', :region_id => 13)
	Commune.create(:name => 'SAN JOAQUIN', :region_id => 13)
	Commune.create(:name => 'SAN JOSE DE MAIPO', :region_id => 13)
	Commune.create(:name => 'SAN MIGUEL', :region_id => 13)
	Commune.create(:name => 'SAN PEDRO', :region_id => 13)
	Commune.create(:name => 'SAN RAMON', :region_id => 13)
	Commune.create(:name => 'SANTIAGO CENTRO', :region_id => 13)
	Commune.create(:name => 'SANTIAGO OESTE', :region_id => 13)
	Commune.create(:name => 'SANTIAGO SUR', :region_id => 13)
	Commune.create(:name => 'TALAGANTE', :region_id => 13)
	Commune.create(:name => 'TIL-TIL', :region_id => 13)
	Commune.create(:name => 'VITACURA', :region_id => 13)
	Commune.create(:name => 'CORRAL', :region_id => 14)
	Commune.create(:name => 'FUTRONO', :region_id => 14)
	Commune.create(:name => 'LA UNION', :region_id => 14)
	Commune.create(:name => 'LAGO RANCO', :region_id => 14)
	Commune.create(:name => 'LANCO', :region_id => 14)
	Commune.create(:name => 'LOS LAGOS', :region_id => 14)
	Commune.create(:name => 'MAFIL', :region_id => 14)
	Commune.create(:name => 'MARIQUINA', :region_id => 14)
	Commune.create(:name => 'VALDIVIA', :region_id => 14)
	Commune.create(:name => 'PANGUIPULLI', :region_id => 14)
	Commune.create(:name => 'PAILLACO', :region_id => 14)
	Commune.create(:name => 'RIO BUENO', :region_id => 14)
	Commune.create(:name => 'ARICA', :region_id => 15)
	Commune.create(:name => 'CAMARONES', :region_id => 15)
	Commune.create(:name => 'GENERAL LAGOS', :region_id => 15)
	Commune.create(:name => 'PUTRE', :region_id => 15)
  end

end

